#!/usr/bin/make -f

image=smbd
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

# runargs=--publish-all
runargs=--publish=137-138:137-138/udp \
	--publish=445:445/tcp
